- set_fact:
    golang: {}

- name: check goenv
  command: |
    bash -lc 'which goenv'
  register: which_goenv
  ignore_errors: yes

- name: install goenv
  command: |
    bash -lc 'anyenv install goenv'
  when: which_goenv.rc > 0

- name: get installed versions
  command: |
    bash -lc 'goenv versions'
  register: installed_versions

- name: install golang
  command: |
    bash -lc 'goenv install {{ item | quote }}'
  when: |
    go.versions and installed_versions.stdout.find(item) == -1
  with_items: '{{ golang.versions }}'

- name: set global golang
  command: |
    bash -lc 'goenv global {{ python.versions[0] | quote }}'
  when: go.versions
